//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pone_Tv.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string First_and_second_name_ { get; set; }
        public string last_name { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Url { get; set; }
        public string Gender { get; set; }
        public byte[] Profile_Photo { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool I_agree { get; set; }
    }
}
